/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as AtualizarSenhaRouteImport } from './routes/atualizar-senha'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as MinhaContaPedidosRouteImport } from './routes/minha-conta.pedidos'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminColecoesRouteImport } from './routes/admin.colecoes'
import { Route as AdminCategoriasHomeRouteImport } from './routes/admin.categorias-home'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAnuncioRouteImport } from './routes/admin.anuncio'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin.produtos.index'
import { Route as AdminProdutosNovoRouteImport } from './routes/admin.produtos.novo'
import { Route as AdminProdutosIdRouteImport } from './routes/admin.produtos.$id'
import { Route as AdminPedidosIdRouteImport } from './routes/admin.pedidos.$id'

const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const AtualizarSenhaRoute = AtualizarSenhaRouteImport.update({
  id: '/atualizar-senha',
  path: '/atualizar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaPedidosRoute = MinhaContaPedidosRouteImport.update({
  id: '/minha-conta/pedidos',
  path: '/minha-conta/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminColecoesRoute = AdminColecoesRouteImport.update({
  id: '/colecoes',
  path: '/colecoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasHomeRoute = AdminCategoriasHomeRouteImport.update({
  id: '/categorias-home',
  path: '/categorias-home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnuncioRoute = AdminAnuncioRouteImport.update({
  id: '/anuncio',
  path: '/anuncio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProdutosRoute,
} as any)
const AdminProdutosNovoRoute = AdminProdutosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminProdutosRoute,
} as any)
const AdminProdutosIdRoute = AdminProdutosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProdutosRoute,
} as any)
const AdminPedidosIdRoute = AdminPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPedidosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/atualizar-senha': typeof AtualizarSenhaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/admin/anuncio': typeof AdminAnuncioRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias-home': typeof AdminCategoriasHomeRoute
  '/admin/colecoes': typeof AdminColecoesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/minha-conta/pedidos': typeof MinhaContaPedidosRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atualizar-senha': typeof AtualizarSenhaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/admin/anuncio': typeof AdminAnuncioRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias-home': typeof AdminCategoriasHomeRoute
  '/admin/colecoes': typeof AdminColecoesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/minha-conta/pedidos': typeof MinhaContaPedidosRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/atualizar-senha': typeof AtualizarSenhaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/admin/anuncio': typeof AdminAnuncioRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias-home': typeof AdminCategoriasHomeRoute
  '/admin/colecoes': typeof AdminColecoesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/minha-conta/pedidos': typeof MinhaContaPedidosRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/atualizar-senha'
    | '/carrinho'
    | '/checkout'
    | '/login'
    | '/loja'
    | '/recuperar-senha'
    | '/admin/anuncio'
    | '/admin/banners'
    | '/admin/categorias-home'
    | '/admin/colecoes'
    | '/admin/configuracoes'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/minha-conta/pedidos'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/admin/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atualizar-senha'
    | '/carrinho'
    | '/checkout'
    | '/login'
    | '/loja'
    | '/recuperar-senha'
    | '/admin/anuncio'
    | '/admin/banners'
    | '/admin/categorias-home'
    | '/admin/colecoes'
    | '/admin/configuracoes'
    | '/admin/pedidos'
    | '/minha-conta/pedidos'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/admin'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/admin/produtos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/atualizar-senha'
    | '/carrinho'
    | '/checkout'
    | '/login'
    | '/loja'
    | '/recuperar-senha'
    | '/admin/anuncio'
    | '/admin/banners'
    | '/admin/categorias-home'
    | '/admin/colecoes'
    | '/admin/configuracoes'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/minha-conta/pedidos'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/admin/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AtualizarSenhaRoute: typeof AtualizarSenhaRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  LojaRoute: typeof LojaRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  MinhaContaPedidosRoute: typeof MinhaContaPedidosRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atualizar-senha': {
      id: '/atualizar-senha'
      path: '/atualizar-senha'
      fullPath: '/atualizar-senha'
      preLoaderRoute: typeof AtualizarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta/pedidos': {
      id: '/minha-conta/pedidos'
      path: '/minha-conta/pedidos'
      fullPath: '/minha-conta/pedidos'
      preLoaderRoute: typeof MinhaContaPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/colecoes': {
      id: '/admin/colecoes'
      path: '/colecoes'
      fullPath: '/admin/colecoes'
      preLoaderRoute: typeof AdminColecoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias-home': {
      id: '/admin/categorias-home'
      path: '/categorias-home'
      fullPath: '/admin/categorias-home'
      preLoaderRoute: typeof AdminCategoriasHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/anuncio': {
      id: '/admin/anuncio'
      path: '/anuncio'
      fullPath: '/admin/anuncio'
      preLoaderRoute: typeof AdminAnuncioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
    '/admin/produtos/novo': {
      id: '/admin/produtos/novo'
      path: '/novo'
      fullPath: '/admin/produtos/novo'
      preLoaderRoute: typeof AdminProdutosNovoRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
    '/admin/produtos/$id': {
      id: '/admin/produtos/$id'
      path: '/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AdminProdutosIdRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
    '/admin/pedidos/$id': {
      id: '/admin/pedidos/$id'
      path: '/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AdminPedidosIdRouteImport
      parentRoute: typeof AdminPedidosRoute
    }
  }
}

interface AdminPedidosRouteChildren {
  AdminPedidosIdRoute: typeof AdminPedidosIdRoute
}

const AdminPedidosRouteChildren: AdminPedidosRouteChildren = {
  AdminPedidosIdRoute: AdminPedidosIdRoute,
}

const AdminPedidosRouteWithChildren = AdminPedidosRoute._addFileChildren(
  AdminPedidosRouteChildren,
)

interface AdminProdutosRouteChildren {
  AdminProdutosIdRoute: typeof AdminProdutosIdRoute
  AdminProdutosNovoRoute: typeof AdminProdutosNovoRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
}

const AdminProdutosRouteChildren: AdminProdutosRouteChildren = {
  AdminProdutosIdRoute: AdminProdutosIdRoute,
  AdminProdutosNovoRoute: AdminProdutosNovoRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
}

const AdminProdutosRouteWithChildren = AdminProdutosRoute._addFileChildren(
  AdminProdutosRouteChildren,
)

interface AdminRouteChildren {
  AdminAnuncioRoute: typeof AdminAnuncioRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriasHomeRoute: typeof AdminCategoriasHomeRoute
  AdminColecoesRoute: typeof AdminColecoesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminPedidosRoute: typeof AdminPedidosRouteWithChildren
  AdminProdutosRoute: typeof AdminProdutosRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnuncioRoute: AdminAnuncioRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriasHomeRoute: AdminCategoriasHomeRoute,
  AdminColecoesRoute: AdminColecoesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminPedidosRoute: AdminPedidosRouteWithChildren,
  AdminProdutosRoute: AdminProdutosRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AtualizarSenhaRoute: AtualizarSenhaRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  LojaRoute: LojaRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  MinhaContaPedidosRoute: MinhaContaPedidosRoute,
  PedidoIdRoute: PedidoIdRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
